### ISSUE TITLE
Save configuration data to local configuration file

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#12]
The app should get a functionality to save and retrieve configuration data from a local file, for example, `settings.json`. This way, it doesn't always have to rely on command-line flags.

The functionality should be added to `internal/settings/settings.go`.

**It should...**

- Look in the user's home folder, i.e. `~/.go-osmand-tracker/settings.json`
- Look in the folder where the app has been started (current working directory)
- ... or use default values and write them to the _current working directory_

**It should not...**

- Crash because the settings file(s) did not exist
- Crash because a settings file is invalid

**Bonus points for...**

- If the user's personal `settings.json` overrules and/or extends the rules in the current working directory. (a.k.a. local settings over global settings)

**Comment by moogacs** [comment]
@ricardobalk, by settings.json you mean , server configurations ! ip:port and so on !

**Comment by ricardobalk** [comment]
> @ricardobalk, by settings.json you mean , server configurations ! ip:port and so on !

Yes @moogacs, basically everything that could be set with the CLI flags should be saved/loaded to/from the settings.json file.

**Comment by moogacs** [comment]
I will pick that one
