### ISSUE TITLE
TLS (SSL) support

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#13]
The app should get support for TLS certificates, provided via the command line and/or local configuration file (see #12).

For example, by using command line flags like `--cert '/path/to/pubkey.pem' --cert-ca '/path/to/ca.pem' --cert-private '/path/to/privkey.pem'`

TLS should be enabled by default, because location data is privacy sensitive and it's a good practice to use TLS by default. If no certificate paths are provided, the user will see a warning and the app will exit. To override this behaviour, the user could add the `--no-tls` flag to disable it.

**Comment by moogacs** [comment]
@ricardobalk, I can pick that if you didn't start working on it !

**Comment by ricardobalk** [comment]
Sure, @moogacs 

Now we have the config in one settings file (#29), could you take a look into this? Obviously, without CLI flags, but extending the `settings.json` :innocent:

And do you also know how to create and use self-signed certificates for development purposes? Otherwise I could help with that :+1:

**Comment by moogacs** [comment]
You mean something like `openssl` or `let's encrypt`!

**Comment by ricardobalk** [comment]
I personally prefer just using certificates that are available on the local machine, that would be more flexible. Like the ones you can also self-generate with `openssl`. Then you can always use Let's Encrypt, but also use your self-signed certs for local development. And others can use certificates from other providers, like Comodo.

I found and altered the following pieces from https://github.com/gin-gonic/gin/issues/1099#issuecomment-341868135 and https://github.com/denji/golang-tls


The following lines...

https://github.com/ricardobalk/go-osmand-tracker/blob/06a06816216e05427caa93df4946a45eeb686937/internal/server/server.go#L159-L162

... should become something like:

```golang
tlsConfig := &tls.Config{
	MinVersion:               tls.VersionTLS12,
	CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
	PreferServerCipherSuites: true,
	CipherSuites: []uint16{
		tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
		tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_RSA_WITH_AES_256_CBC_SHA,
	},
}

server := http.Server{
	Addr:      listenAddr,
	Handler:   ginEngine,
	TLSConfig: tlsConfig,
}

err := server.ListenAndServeTLS("server.crt", "server.key") // TODO: Make this load from settings.json
if err != nil {
	log.Fatal(err)
}
```

Please try to merge this code, let it load the values of `server.crt` and `server.key` from the configuration file, and test it with a certificate. Let me know if that works! :+1:

**Comment by ricardobalk** [comment]
As #44 has been merged, this issue can be closed :+1:
