### ISSUE TITLE
Add debug CLI flag

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#19]
There should be a `--debug` CLI flag.

**Default behaviour**
- Default behaviour is to not output anything to the console, except informative messages ("Server started on port xxxx").
- The Gin router runs in "release" mode. (`gin.SetMode(gin.ReleaseMode)`)

**Debug mode**
- Allows more verbose messages.
- The Gin router runs in "debug" mode

**Comment by moogacs** [comment]
Hi there, I will pick that one
