### ISSUE TITLE
Remove CLI arguments, only keep a --config

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#28]
So, it seemed that passing CLI arguments were not the best way to configure this application, and a configuration file like `settings.json` is much more convenient.

We're aiming to solely rely on a single configuration file, either one that's in the apps' root directory or one passed via `--config`. Less (double) code makes the application more maintainable and less prone to errors.

**Comment by moogacs** [comment]
I will work on that one

**Comment by moogacs** [comment]
@ricardobalk I am suggesting renaming the file to `config.json` or `tracker-config.json` instead of `settings`, what do you think it make sense to avoid any conflicts
