### ISSUE TITLE
Saving tracks (database integration)

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#3]
The current app only saves the last known location. There is no database that can save tracks.

**Comment by raydwaipayan** [comment]
For saving previous locations, we have two options:

1) A vector which stores all locations submitted so far in memory. (non persistent)
2) Db engine like BoltDB to store the entries somewhere in storage. (persistent)

Which are you aiming at?

**Comment by ricardobalk** [comment]
I was aiming at option 2. A persistent database that could save tracks even between restarts of the app. Preferably with multi-user support, or at least ready for it (see #2)

- Could be BoltDB, I've just been reading into it. Depending on your experience with it, you could give it a shot.
- Something like [sqlite](https://www.bogotobogo.com/GoLang/GoLang_SQLite.php) might also work (and sqlite could be opened with sqlite viewer apps, as a nice addition)
- [MongoDB](https://www.mongodb.com/golang)

What's your opinion on this?

**Comment by raydwaipayan** [comment]
Maybe bolt or sqlite. Mongo is way heavy for the current purpose.

Considering there is very little relation between data, a nosql
db might be the to-go here. So perhaps bolt.
