### ISSUE TITLE
Custom port CLI flag

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/go-osmand-tracker#4]
It's currently not possible to set the port from the command line. Should become possible by giving a command-line flag like `--port 9000`

**Comment by atrievel** [comment]
@ricardobalk - I'd like to take this if it s available

**Comment by ricardobalk** [comment]
Sure @atrievel, please go ahead. If you need help with something, feel free to send me a message here or elsewhere ([Keybase](https://keybase.io/ricardobalk), [Mastodon](https://mastodon.social/@ricardobalk), [Twitter](https://twitter.com/ricardobalk))

**Comment by ricardobalk** [comment]
@atrievel You could use the `flags` package that was provided by the Go team. An example of using the `flags` package could be found in my other Go app [go-fetch-scrobbles](https://github.com/ricardobalk/go-fetch-scrobbles), but @kf5grd informed me that [urfave/cli](https://github.com/urfave/cli) is a great package to handle CLI arguments.

**Comment by atrievel** [comment]
@ricardobalk - thank you. I have this done already - I was just waiting for Oct. 1st before submitting any PRs. I'll be submitting it soon
